spring:
  security:
    oauth2:
      client:
        registration:
          github: 
            client-id: CLIENT_ID
            client-secret: SECRET_KEY
            
          google:
            client-id: CLIENT_ID
            client-secret: SECRET_KEY